# 基本設定
baseURL = 'https://tarrragon.github.io/blog/'
theme = 'hugo-bearcub'
copyright = 'Tarragon (CC BY 4.0)'
defaultContentLanguage = 'zh-tw'

# 產生 robots.txt 以利於 SEO
enableRobotsTXT = true

# 摘要設定
summaryLength = 200  # 摘要字數限制

# 設定語法高亮
[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

# 多語言模式設定
[languages]
  [languages.zh-tw]
    title = 'Tarragon'
    languageName = 'zh-TW 🇹🇼'
    LanguageCode = 'zh-TW'
    contentDir = 'content'
    [languages.zh-tw.params]
      madeWith = '使用 [hugo](https://gohugo.io/) 製作'

# 導航選單設定
[menu]

  [[menu.main]]
    name = "搜尋"
    url = "/search/"
    weight = 1

  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 5

  [[menu.main]]
    name = "標籤"
    url = "/tags/"
    weight = 10
  
 

[params]
  # 網站描述
  description = '一個部落格'

  # 網站標題
  title = 'Tarragon'

  # 日期格式
  dateFormat = '2006-01-02'

  # 主題樣式 (original 或 herman)
  themeStyle = 'herman'

  # 自動產生社群媒體卡片
  generateSocialCard = true

  # 作者資訊
  [params.author]
    name = 'tarragon'

#永久連結
[permalinks]
  posts = "/posts/:slug/"
  work-log = "/work-log/:slug/"
  record = "/record/:slug/"
  other = "/other/:slug/"